# Generated by Django 6.0.3 on 2026-03-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(help_text='ex: 2023 — Présent', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Votre Nom', max_length=100)),
                ('title', models.CharField(default='Développeur Full Stack', max_length=200)),
                ('bio', models.TextField(help_text="Description pour la section 'À Propos'")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('status', models.CharField(default='Disponible pour missions', max_length=50)),
                ('projects_count', models.IntegerField(default=15)),
                ('experience_years', models.IntegerField(default=3)),
                ('tech_count', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(choices=[('dev', 'Développement'), ('reseau', 'Réseau & Infra')], default='dev', max_length=20)),
                ('project_type', models.CharField(default='Web App', help_text='ex: Web App, Mobile, API', max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(help_text='Séparez par des virgules: Django, React, MySQL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Classe Font Awesome ex: fas fa-server', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex: Back-End, Front-End...', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Classe Font Awesome ex: fab fa-github', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text='Classe Devicon ex: devicon-django-plain', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillcategory')),
            ],
        ),
    ]
