# Generated by Django 6.0.3 on 2026-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='css_class',
            field=models.CharField(default='cat-backend', help_text='ex: cat-backend, cat-frontend...', max_length=50),
        ),
    ]
