# Generated by Django 6.0.3 on 2026-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skillcategory_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(default='votre.email@exemple.com', help_text="L'adresse où vous recevrez les messages du formulaire de contact", max_length=254),
        ),
    ]
